// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type SignInReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type SignUpReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type SignUpResp struct {
	UserId string `json:"user_id"`
}

type TokenReq struct {
	RefreshToken string `json:"refresh_token"`
}

type TokenResp struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
	ExpiresIn    int64  `json:"expires_in"`
	TokenType    string `json:"token_type"`
}

type UserResp struct {
	Id       string `json:"id"`
	Username string `json:"username"`
}
