// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	auth "auth4x/internal/handler/auth"
	health "auth4x/internal/handler/health"
	users "auth4x/internal/handler/users"
	"auth4x/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/auth/sign-in",
				Handler: auth.SignInHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/auth/sign-up",
				Handler: auth.SignUpHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/auth/token",
				Handler: auth.TokenHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/ping",
				Handler: health.PingHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/users/me",
				Handler: users.UserMeHandler(serverCtx),
			},
		},
	)
}
